print("-----------------------------------------------------------")
print(" calculo de IMC")
print("-----------------------------------------------------------")
peso = float(input("Digite seu peso em KG: "))
altura = float(input ("Digite sua altura em cm: "))
imc = peso / (altura ** 2)
print("seu IMC atualizado é de: ",imc)
